'use client'
import React, {useEffect, useState} from 'react';
import {MessageSquareDot, Send} from "lucide-react";
import AiMessage from "@/components/ai-message";



function PreviewChat({appearanceColor, companyName}) {
    const [chatIconClicked, setChatIconClicked] = useState(true)



    return (
        <div className='absolute bottom-2 right-2'>
            {chatIconClicked && <div className='bottom-14 flex flex-col relative h-[350px] w-[350px] bg-gray-50 border-gray-300 shadow-sm rounded-md border'>
                <div className='flex py-2 px-2 items-center gap-4' style={{backgroundColor: appearanceColor}}>
                    <div className='rounded-full w-10 h-10 bg-black'></div>
                    <div className='text-white'>{companyName}</div>
                </div>

                <div className='flex-1 overflow-y-scroll py-3'>
                    <div className='text-sm px-4 py-2 bg-gray-100 mt-2 rounded-r-md text-balance text-gray-700 w-fit max-w-[70%]'>This will be the body. This message can be really long because it will be generated by AI and AI likes and loves to yap.</div>
                    <AiMessage message='If you’d like, I can also write the backend Node.js/Next.js version, or help you store the file path in your database alongside metadata.

Would you like an example of that?'/>
                    <AiMessage message='If you’d like, I can also write the backend Node.js/Next.js version, or help you store the file path in your database alongside metadata.

Would you like an example of that?'/>


                    <div className='text-sm px-4 py-2 mt-2 bg-green-100 rounded-l-md text-gray-700 w-fit max-w-[70%] ml-auto'>This message will be sent by the user.</div>
                </div>

                <div className='flex border-b rounded-b-lg'>
                    <input className='outline-0 py-3 flex-1 px-2 text-sm' placeholder='type your message here.'/>
                    <button className='bg-white text-gray-500 px-3'><Send size='20px'/></button>
                </div>
            </div>}
            <div style={{backgroundColor: appearanceColor}} onClick={() => setChatIconClicked(prev => !prev)} className='rounded-full px-3 py-3 text-white absolute bottom-0 right-0'><div><MessageSquareDot/></div></div>
        </div>
    );
}

export default PreviewChat;